#!/bin/sh

### BEGIN INIT INFO
# Provides:          service-dnsforever-dns
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the Netsarang test server
# Description:       starts Netsarang test using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON_PATH=/service/dnsforever-dns
DAEMON=$DAEMON_PATH/run
DAEMON_ARGS="dnsforever.kr"
DAEMON_USER=root
DAEMON_LOGPATH=$DAEMON_PATH/dns.log
DAEMON_VENV=$DAEMON_PATH/venv
NAME=service-dnsforever-dns
DESC=service-dnsforever-dns

test -x $DAEMON || exit 0

set -e

. $DAEMON_VENV/bin/activate

. /lib/lsb/init-functions

case "$1" in
	start)
		echo -n "Starting $DESC: "
		if [ -n "$ULIMIT" ]; then
			# Set the ulimits
			ulimit $ULIMIT
		fi
		start-stop-daemon --start --quiet --chuid $DAEMON_USER    \
		     --make-pidfile --pidfile /var/run/$NAME.pid --background       \
		     --startas /bin/bash -- -c "exec $DAEMON $DAEMON_ARGS >> $DAEMON_LOGPATH 2>&1" || true
		echo "$NAME."
		;;

	stop)
		echo -n "Stopping $DESC: "
		start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid --signal 9 || true
		echo "$NAME."
		;;

	restart|force-reload)
		echo -n "Restarting $DESC: "
		start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid --signal 9 || true
		sleep 1
		start-stop-daemon --start --quiet --chuid $DAEMON_USER    \
		     --make-pidfile --pidfile /var/run/$NAME.pid --background       \
		     --startas /bin/bash -- -c "exec $DAEMON $DAEMON_ARGS >> $DAEMON_LOGPATH 2>&1" || true
		echo "$NAME."
		;;

	*)
		echo "Usage: $NAME {start|stop|restart|reload|force-reload|status|configtest}" >&2
		exit 1
		;;
esac

exit 0
